patterns:
  - pattern: |
      {
        cookie: $<!>$<HASH_CONTENT>
      }
    filters:
      - variable: HASH_CONTENT
        detection: express_default_cookie_config_hash_val
      - either:
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_name_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_expiry_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_path_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_domain_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_secure_attribute
  - pattern: |
      cookieSession($<!>$<HASH_CONTENT>)
    filters:
      - variable: HASH_CONTENT
        detection: express_default_cookie_config_hash_val
      - either:
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_name_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_expiry_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_path_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_domain_attribute
        - not:
            variable: HASH_CONTENT
            detection: express_default_cookie_config_secure_attribute
languages:
  - javascript
auxiliary:
  - id: express_default_cookie_config_hash_val
    patterns:
    - |
      {}
  - id: express_default_cookie_config_name_attribute
    patterns:
    - |
      { name: $<_> }
  - id: express_default_cookie_config_expiry_attribute
    patterns:
    - |
      { maxAge: $<_> }
    - |
      { expires: $<_> }
  - id: express_default_cookie_config_path_attribute
    patterns:
    - |
      { path: $<_> }
  - id: express_default_cookie_config_domain_attribute
    patterns:
    - |
      { domain: $<_> }
  - id: express_default_cookie_config_secure_attribute
    patterns:
    - |
      { secure: $<_> }
severity: medium
metadata:
  description: "Cookie with default config detected."
  remediation_message: |
    ## Description
    To make sure cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

    ## Remediations
    ✅ Instead of the default cookie name, use generic names.

    ✅ Always set a maxAge or expires value

    ## Resources
    - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
  cwe_id:
    - 523
    - 522
  id: "express_default_cookie_config"
