patterns:
  - pattern: |
      session($<!>$<HASH_CONTENT>)
    filters:
      - not:
          variable: HASH_CONTENT
          detection: express_default_session_config_name_attribute
languages:
  - javascript
auxiliary:
  - id: express_default_session_config_name_attribute
    patterns:
    - |
      { name: $<_> }
trigger: presence
severity: medium
metadata:
  description: "Session cookie with default config detected."
  remediation_message: |
    ## Description
    To make sure session cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

    ## Remediations
    âœ… Instead of the default session name, use generic names.

    ## Resources
    - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
  cwe_id:
    - 523
    - 522
  id: "express_default_session_config"
