medium:
    - rule:
        cwe_ids:
            - "201"
        id: ruby_third_parties_google_dataflow
        description: Sensitive data sent to Google Dataflow detected.
        documentation_url: https://docs.bearer.com/reference/rules/ruby_third_parties_google_dataflow
      line_number: 8
      filename: datatype_in_config.rb
      category_groups:
        - PII
      parent_line_number: 8
      snippet: 'config.metadata = { current_user_id: current_user.email }'
      fingerprint: fb099f5471cad3cd03de3274fbd6d9d8_0
    - rule:
        cwe_ids:
            - "201"
        id: ruby_third_parties_google_dataflow
        description: Sensitive data sent to Google Dataflow detected.
        documentation_url: https://docs.bearer.com/reference/rules/ruby_third_parties_google_dataflow
      line_number: 14
      filename: datatype_in_config.rb
      category_groups:
        - PII
      parent_line_number: 14
      snippet: 'client_config.metadata = { current_user_id: current_user.email }'
      fingerprint: fb099f5471cad3cd03de3274fbd6d9d8_1

