warning:
    - rule_dsrid: DSR-10
      rule_display_id: ruby_rails_default_encryption
      rule_description: Force application-level encryption when processing sensitive data.
      rule_documentation_url: https://curio.sh/reference/rules/ruby_rails_default_encryption
      line_number: 3
      filename: application_level_encryption_missing/schema_rb/db/schema.rb
      category_groups:
        - PII
      parent_line_number: 2
      parent_content: |-
        create_table "users", force: :cascade do |t|
            t.string "email", null: false
            t.string "name"
            t.string "encrypted_password", null: false
            t.datetime "created_at", null: false
            t.datetime "updated_at", null: false
          end
    - rule_dsrid: DSR-10
      rule_display_id: ruby_rails_default_encryption
      rule_description: Force application-level encryption when processing sensitive data.
      rule_documentation_url: https://curio.sh/reference/rules/ruby_rails_default_encryption
      line_number: 4
      filename: application_level_encryption_missing/schema_rb/db/schema.rb
      category_groups:
        - PII
      parent_line_number: 2
      parent_content: |-
        create_table "users", force: :cascade do |t|
            t.string "email", null: false
            t.string "name"
            t.string "encrypted_password", null: false
            t.datetime "created_at", null: false
            t.datetime "updated_at", null: false
          end


